# Generated by Django 4.1 on 2022-08-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descr', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
